# Generated by Django 4.2.1 on 2023-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoty',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
