# Generated by Django 4.2.1 on 2023-05-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_categoty_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
    ]
