# Generated by Django 4.2.1 on 2023-06-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='razor_pay_status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='razor_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='razorpay_order_id',
        ),
    ]
