# Generated by Django 4.2.1 on 2023-06-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0002_rename_order_id_payment_razor_pay_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razor_payment_id',
            new_name='razorpay_payment_id',
        ),
    ]
