# Generated by Django 4.2.1 on 2023-06-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0003_rename_razor_payment_id_payment_razorpay_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
