# Generated by Django 4.2.1 on 2023-06-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0004_remove_order_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=True),
        ),
    ]
