# Generated by Django 4.2.1 on 2023-07-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0005_order_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
